-- Migration 00037: Pub Gas Category and 10 Products Setup
-- Creates the Pub Gas category and inserts/updates the 10 real products in public.products

-- 1. Insert / Update Pub Gas category
INSERT INTO public.categories (
  name,
  slug,
  icon,
  description,
  subcategories,
  display_order,
  is_active
) VALUES (
  'Pub Gas',
  'pub-gas',
  'UtensilsCrossed',
  'Food-grade dispense gases and accessories for pubs, bars, restaurants and breweries across Gloucestershire. (Pub customers only for cellar gases).',
  ARRAY[
    'CO2 / Carbon Dioxide',
    'Mixed Gas',
    'Pub Gas Spanner',
    'Mixed Gas O-ring',
    'CO2 O-ring'
  ],
  2,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  icon = EXCLUDED.icon,
  description = EXCLUDED.description,
  subcategories = EXCLUDED.subcategories,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active;

-- 2. Insert or update the 10 real Pub Gas products
INSERT INTO public.products (
  name,
  slug,
  brand,
  category_slug,
  subcategory,
  description,
  price,
  stock,
  rating,
  reviews_count,
  image_url,
  is_featured,
  is_offer,
  specs,
  created_at,
  updated_at
) VALUES
  (
    '6.35kg Carbon Dioxide',
    '6-35kg-carbon-dioxide',
    'Stayte Pub Gas',
    'pub-gas',
    'CO2 / Carbon Dioxide',
    '6.35kg food-grade Carbon Dioxide (CO2) cylinder for draught beer, cider and soft drinks dispense. Restricted to pub and licensed hospitality customers.',
    28.80,
    25,
    5.0,
    8,
    '/pub-gas-co2-0-35kg.png',
    true,
    false,
    '{"gas_type": "Pub Gas", "is_active": true, "is_refill": true, "usage_type": "COMMERCIAL", "product_mode": "Refill / Cylinder Exchange", "refill_price": 28.80, "cylinder_size": "6.35kg", "restricted_to": "Pub customers only", "empty_cylinder_required": true}'::jsonb,
    now(),
    now()
  ),
  (
    '10L 30/70 Mixed Gas',
    '10l-30-70-mixed-gas',
    'Stayte Pub Gas',
    'pub-gas',
    'Mixed Gas',
    '10L 30% CO2 / 70% Nitrogen dispense gas mixture for creamy stouts, smooth ales and draught bitters. Restricted to pub and licensed hospitality customers.',
    25.20,
    30,
    5.0,
    14,
    '/pub-gas-mixed-10l-30-70.png',
    true,
    false,
    '{"gas_type": "Pub Gas", "is_active": true, "is_refill": true, "usage_type": "COMMERCIAL", "product_mode": "Refill / Cylinder Exchange", "refill_price": 25.20, "cylinder_size": "10L", "mixture": "30/70", "restricted_to": "Pub customers only", "empty_cylinder_required": true}'::jsonb,
    now(),
    now()
  ),
  (
    '10L 50/50 Mixed Gas',
    '10l-50-50-mixed-gas',
    'Stayte Pub Gas',
    'pub-gas',
    'Mixed Gas',
    '10L 50% CO2 / 50% Nitrogen dispense gas mixture for craft beers, ales and designated draught lines. Restricted to pub and licensed hospitality customers.',
    27.00,
    20,
    5.0,
    9,
    '/pub-gas-mixed-10l-50-50.png',
    true,
    false,
    '{"gas_type": "Pub Gas", "is_active": true, "is_refill": true, "usage_type": "COMMERCIAL", "product_mode": "Refill / Cylinder Exchange", "refill_price": 27.00, "cylinder_size": "10L", "mixture": "50/50", "restricted_to": "Pub customers only", "empty_cylinder_required": true}'::jsonb,
    now(),
    now()
  ),
  (
    '10L 60/40 Mixed Gas',
    '10l-60-40-mixed-gas',
    'Stayte Pub Gas',
    'pub-gas',
    'Mixed Gas',
    '10L 60% CO2 / 40% Nitrogen dispense gas mixture for lagers, ciders and highly carbonated draught drinks. Restricted to pub and licensed hospitality customers.',
    28.80,
    35,
    5.0,
    18,
    '/pub-gas-mixed-10l-60-40.png',
    true,
    false,
    '{"gas_type": "Pub Gas", "is_active": true, "is_refill": true, "usage_type": "COMMERCIAL", "product_mode": "Refill / Cylinder Exchange", "refill_price": 28.80, "cylinder_size": "10L", "mixture": "60/40", "restricted_to": "Pub customers only", "empty_cylinder_required": true}'::jsonb,
    now(),
    now()
  ),
  (
    '47L 30/70 Mixed Gas',
    '47l-30-70-mixed-gas',
    'Stayte Pub Gas',
    'pub-gas',
    'Mixed Gas',
    'High-capacity 47L 30% CO2 / 70% Nitrogen dispense cylinder for busy pub cellars and high-turnover draught venues. Restricted to pub and licensed hospitality customers.',
    68.40,
    15,
    5.0,
    12,
    '/pub-gas-mixed-47l-30-70.png',
    true,
    false,
    '{"gas_type": "Pub Gas", "is_active": true, "is_refill": true, "usage_type": "COMMERCIAL", "product_mode": "Refill / Cylinder Exchange", "refill_price": 68.40, "cylinder_size": "47L", "mixture": "30/70", "restricted_to": "Pub customers only", "empty_cylinder_required": true}'::jsonb,
    now(),
    now()
  ),
  (
    'Pub Gas Spanner (CO2 and Mixed)',
    'pub-gas-spanner-co2-and-mixed',
    'Stayte Pub Gas',
    'pub-gas',
    'Pub Gas Spanner',
    'Heavy-duty dual-ended combination spanner designed for tightening and changing both CO2 and Mixed Gas cylinder regulator connections securely.',
    5.95,
    50,
    5.0,
    22,
    '/pub-gas-spanner.png',
    false,
    false,
    '{"gas_type": "Hardware & Adapter", "is_active": true, "is_refill": false, "usage_type": "COMMERCIAL", "product_mode": "Outright Purchase", "empty_cylinder_required": false}'::jsonb,
    now(),
    now()
  ),
  (
    'Mixed Gas O-ring',
    'mixed-gas-o-ring',
    'Stayte Pub Gas',
    'pub-gas',
    'Mixed Gas O-ring',
    'Replacement sealing O-rings for Mixed Gas bottle valves and secondary regulators. Prevents cellar gas leaks and maintains optimal line pressure.',
    1.50,
    100,
    5.0,
    30,
    '/pub-gas-mixed-oring.png',
    false,
    false,
    '{"gas_type": "Hardware & Adapter", "is_active": true, "is_refill": false, "usage_type": "COMMERCIAL", "product_mode": "Outright Purchase", "empty_cylinder_required": false}'::jsonb,
    now(),
    now()
  ),
  (
    'CO2 O-ring',
    'co2-o-ring',
    'Stayte Pub Gas',
    'pub-gas',
    'CO2 O-ring',
    'High-durability sealing O-rings specifically sized for CO2 Carbon Dioxide cylinder valves and cellar regulators.',
    1.50,
    100,
    5.0,
    28,
    '/pub-gas-co2-oring.png',
    false,
    false,
    '{"gas_type": "Hardware & Adapter", "is_active": true, "is_refill": false, "usage_type": "COMMERCIAL", "product_mode": "Outright Purchase", "empty_cylinder_required": false}'::jsonb,
    now(),
    now()
  ),
  (
    '22.6kg Carbon Dioxide',
    '22-6kg-carbon-dioxide',
    'Stayte Pub Gas',
    'pub-gas',
    'CO2 / Carbon Dioxide',
    '22.6kg food-grade Carbon Dioxide (CO2) cellar cylinder for high-volume soft drinks and draught beer dispense. Restricted to pub and licensed hospitality customers.',
    69.00,
    20,
    5.0,
    16,
    '/pub-gas-co2-22-6kg.png',
    true,
    false,
    '{"gas_type": "Pub Gas", "is_active": true, "is_refill": true, "usage_type": "COMMERCIAL", "product_mode": "Refill / Cylinder Exchange", "refill_price": 69.00, "cylinder_size": "22.6kg", "restricted_to": "Pub customers only", "empty_cylinder_required": true}'::jsonb,
    now(),
    now()
  ),
  (
    '34kg Carbon Dioxide',
    '34kg-carbon-dioxide',
    'Stayte Pub Gas',
    'pub-gas',
    'CO2 / Carbon Dioxide',
    'Large 34kg industrial/commercial food-grade Carbon Dioxide cylinder for multi-line pub cellars, clubs and brewery taprooms. Restricted to pub and licensed hospitality customers.',
    97.20,
    15,
    5.0,
    20,
    '/pub-gas-co2-34kg.png',
    true,
    false,
    '{"gas_type": "Pub Gas", "is_active": true, "is_refill": true, "usage_type": "COMMERCIAL", "product_mode": "Refill / Cylinder Exchange", "refill_price": 97.20, "cylinder_size": "34kg", "restricted_to": "Pub customers only", "empty_cylinder_required": true}'::jsonb,
    now(),
    now()
  )
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  category_slug = EXCLUDED.category_slug,
  subcategory = EXCLUDED.subcategory,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  stock = EXCLUDED.stock,
  image_url = EXCLUDED.image_url,
  specs = EXCLUDED.specs,
  updated_at = now();
