-- Migration 00039: Coal & Other Fuels Category and 20 Products Setup
-- Creates/Updates the "Coal & Other Fuels" category with subcategories (All, Smokeless Fuel, Kiln Dried Logs, Kindling & Heat Logs, Charcoal, Firelighters, Barbecue) and inserts/updates the 20 real products in public.products

-- 1. Insert / Update Coal & Other Fuels category
INSERT INTO public.categories (
  name,
  slug,
  icon,
  description,
  subcategories,
  display_order,
  is_active
) VALUES (
  'Coal & Other Fuels',
  'coal-fuels',
  'Logs',
  'HETAS and Defra approved Ready-to-Burn domestic fuels, smokeless coal, kiln-dried logs, kindling, charcoal and heating fuels.',
  ARRAY[
    'All',
    'Smokeless Fuel',
    'Kiln Dried Logs',
    'Kindling & Heat Logs',
    'Charcoal',
    'Firelighters',
    'Barbecue'
  ],
  3,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  icon = EXCLUDED.icon,
  description = EXCLUDED.description,
  subcategories = EXCLUDED.subcategories,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active;

-- Also ensure legacy coal-logs category slug redirects cleanly to Coal & Other Fuels
INSERT INTO public.categories (
  name,
  slug,
  icon,
  description,
  subcategories,
  display_order,
  is_active
) VALUES (
  'Coal & Other Fuels',
  'coal-logs',
  'Logs',
  'HETAS and Defra approved Ready-to-Burn domestic fuels, smokeless coal, kiln-dried logs, kindling, charcoal and heating fuels.',
  ARRAY[
    'All',
    'Smokeless Fuel',
    'Kiln Dried Logs',
    'Kindling & Heat Logs',
    'Charcoal',
    'Firelighters',
    'Barbecue'
  ],
  3,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  icon = EXCLUDED.icon,
  description = EXCLUDED.description,
  subcategories = EXCLUDED.subcategories,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active;

-- 2. Insert or update the 20 real Coal & Other Fuels products
INSERT INTO public.products (
  name,
  slug,
  brand,
  category_slug,
  subcategory,
  description,
  price,
  stock,
  rating,
  reviews_count,
  image_url,
  is_featured,
  is_offer,
  specs,
  created_at,
  updated_at
) VALUES
  (
    'Brazier - 10kg',
    'brazier-10kg',
    'Brazier',
    'coal-fuels',
    'Smokeless Fuel',
    'Brazier smokeless fuel (10kg) – value for money smokeless fuel for open fires and multi-fuel stoves.',
    6.50,
    50,
    5.0,
    12,
    '/fuel-brazier-10kg.png',
    true,
    false,
    '{"fuel_type": "Smokeless Coal", "weight": "10kg", "is_active": true, "usage_type": "DOMESTIC"}'::jsonb,
    now(),
    now()
  ),
  (
    'Brazier - 20kg',
    'brazier-20kg',
    'Brazier',
    'coal-fuels',
    'Smokeless Fuel',
    'Brazier smokeless fuel (20kg) – 24% hotter and produces up to 80% less smoke. Suitable for open fires and multi-fuel stoves.',
    12.75,
    45,
    5.0,
    18,
    '/fuel-brazier-20kg.png',
    true,
    false,
    '{"fuel_type": "Smokeless Coal", "weight": "20kg", "is_active": true, "usage_type": "DOMESTIC"}'::jsonb,
    now(),
    now()
  ),
  (
    'Coffee Bricks - 7kg',
    'coffee-bricks-7kg',
    'Homefire',
    'coal-fuels',
    'Kindling & Heat Logs',
    'Homefire Coffee Bricks (7kg) – eco-friendly briquettes made from recycled coffee grounds for open fires, chimineas and stoves.',
    7.75,
    35,
    5.0,
    9,
    '/fuel-coffee-bricks-7kg.png',
    true,
    false,
    '{"fuel_type": "Eco Briquettes", "weight": "7kg", "is_active": true, "usage_type": "DOMESTIC"}'::jsonb,
    now(),
    now()
  ),
  (
    'Homefire Twizlers (Wood Wool) Natural Firelighters',
    'homefire-twizlers-wood-wool-natural-firelighters',
    'Homefire',
    'coal-fuels',
    'Firelighters',
    'Homefire Twizlers wood wool firelighters – 100% natural, odorless and quick to light for open fires and multi-fuel stoves.',
    2.30,
    100,
    5.0,
    32,
    '/fuel-homefire-twizlers.png',
    false,
    false,
    '{"fuel_type": "Firelighters", "is_active": true, "usage_type": "DOMESTIC"}'::jsonb,
    now(),
    now()
  ),
  (
    'Kiln Dried Kindling',
    'kiln-dried-kindling',
    'Stayte Fuels',
    'coal-fuels',
    'Kindling & Heat Logs',
    'Premium kiln dried kindling wood – ideal starter fuel for open fires, log burners and chimineas.',
    4.00,
    80,
    5.0,
    24,
    '/fuel-kiln-dried-kindling.png',
    true,
    false,
    '{"fuel_type": "Kindling Wood", "is_active": true, "usage_type": "DOMESTIC"}'::jsonb,
    now(),
    now()
  ),
  (
    'Stoveflame Original 25kg',
    'stoveflame-original-25kg',
    'National Coal',
    'coal-fuels',
    'Smokeless Fuel',
    'Stoveflame Original 25kg smokeless fuel ovoids for multi-fuel stoves, roomheaters and boilers.',
    18.25,
    40,
    5.0,
    15,
    '/fuel-stoveflame-25kg.png',
    true,
    false,
    '{"fuel_type": "Smokeless Ovoids", "weight": "25kg", "is_active": true, "usage_type": "DOMESTIC"}'::jsonb,
    now(),
    now()
  ),
  (
    'Taybrite - 25kg',
    'taybrite-25kg',
    'Taybrite',
    'coal-fuels',
    'Smokeless Fuel',
    'Taybrite 25kg multi-purpose economy smokeless fuel for room heaters, boilers and multi-fuel stoves.',
    18.75,
    40,
    5.0,
    20,
    '/fuel-taybrite-25kg.png',
    true,
    false,
    '{"fuel_type": "Smokeless Fuel", "weight": "25kg", "is_active": true, "usage_type": "DOMESTIC"}'::jsonb,
    now(),
    now()
  ),
  (
    'Homefire - 25kg',
    'homefire-25kg',
    'Homefire',
    'coal-fuels',
    'Smokeless Fuel',
    'Homefire 25kg premier smokeless coal for open fires and multi-fuel stoves. Up to 33% more heat and burns for up to 9 hours.',
    21.15,
    50,
    5.0,
    28,
    '/fuel-homefire-25kg.png',
    true,
    false,
    '{"fuel_type": "Smokeless Coal", "weight": "25kg", "is_active": true, "usage_type": "DOMESTIC"}'::jsonb,
    now(),
    now()
  ),
  (
    'Net of Logs - Approx 10kg',
    'net-of-logs-approx-10kg',
    'Stayte Fuels',
    'coal-fuels',
    'Kiln Dried Logs',
    'Net bag of seasoned hardwood logs (approx 10kg) for open fireplaces and wood-burning stoves.',
    5.25,
    60,
    5.0,
    22,
    '/fuel-net-of-logs-10kg.png',
    true,
    false,
    '{"fuel_type": "Hardwood Logs", "weight": "approx 10kg", "is_active": true, "usage_type": "DOMESTIC"}'::jsonb,
    now(),
    now()
  ),
  (
    'Homefire Kiln Dried Logs - Approx 8kg',
    'homefire-kiln-dried-logs-approx-8kg',
    'Homefire',
    'coal-fuels',
    'Kiln Dried Logs',
    'Homefire premium kiln dried hardwood logs (approx 8kg) – Ready to Burn certified with moisture content under 20%.',
    8.00,
    45,
    5.0,
    19,
    '/fuel-homefire-kiln-dried-logs-8kg.png',
    true,
    false,
    '{"fuel_type": "Kiln Dried Hardwood", "weight": "approx 8kg", "is_active": true, "usage_type": "DOMESTIC"}'::jsonb,
    now(),
    now()
  ),
  (
    'Pre-packed Paraffin 4L',
    'pre-packed-paraffin-4l',
    'Barrettine',
    'coal-fuels',
    'Firelighters',
    'Barrettine premium pre-packed paraffin (4 Litres) for greenhouse heaters, domestic paraffin heaters and lamps.',
    10.00,
    30,
    5.0,
    14,
    '/fuel-pre-packed-paraffin-4l.png',
    false,
    false,
    '{"fuel_type": "Paraffin", "volume": "4L", "is_active": true, "usage_type": "DOMESTIC"}'::jsonb,
    now(),
    now()
  ),
  (
    'Instant Lighting Firelog - Single',
    'instant-lighting-firelog-single',
    'Big K',
    'coal-fuels',
    'Firelighters',
    'Big K instant lighting firelog (single) – just light the wrapper for up to 2 hours of warm ambient fire.',
    2.00,
    75,
    5.0,
    16,
    '/fuel-instant-lighting-firelog.png',
    false,
    false,
    '{"fuel_type": "Instant Firelog", "is_active": true, "usage_type": "DOMESTIC"}'::jsonb,
    now(),
    now()
  ),
  (
    'Heat Logs Hollow - wrapped pack of 12',
    'heat-logs-hollow-wrapped-pack-of-12',
    'Stayte Fuels',
    'coal-fuels',
    'Kindling & Heat Logs',
    'Hollow heat logs (wrapped pack of 12) – high-density compressed sawdust logs. Maximum 10 packs per order.',
    7.35,
    50,
    5.0,
    17,
    '/fuel-heat-logs-hollow-12.png',
    true,
    false,
    '{"fuel_type": "Heat Logs", "quantity": "Pack of 12", "max_quantity": 10, "is_active": true, "usage_type": "DOMESTIC"}'::jsonb,
    now(),
    now()
  ),
  (
    'Net of Kindling - Approx 5kg',
    'net-of-kindling-approx-5kg',
    'Stayte Fuels',
    'coal-fuels',
    'Kindling & Heat Logs',
    'Net bag of dry kindling sticks (approx 5kg) for lighting log fires and stoves effortlessly.',
    4.45,
    60,
    5.0,
    21,
    '/fuel-net-of-kindling-5kg.png',
    true,
    false,
    '{"fuel_type": "Kindling", "weight": "approx 5kg", "is_active": true, "usage_type": "DOMESTIC"}'::jsonb,
    now(),
    now()
  ),
  (
    'Instant Lighting Charcoal - 2kg',
    'instant-lighting-charcoal-2kg',
    'Big K',
    'coal-fuels',
    'Charcoal',
    'Big K instant lighting charcoal (2kg pack) – ready to cook in 20 minutes with no firelighters required.',
    4.50,
    45,
    5.0,
    13,
    '/fuel-instant-lighting-charcoal-2kg.png',
    false,
    false,
    '{"fuel_type": "Instant Charcoal", "weight": "2kg", "is_active": true, "usage_type": "DOMESTIC"}'::jsonb,
    now(),
    now()
  ),
  (
    'Heat Log Blocks - Pack of 8',
    'heat-log-blocks-pack-of-8',
    'CPL',
    'coal-fuels',
    'Kindling & Heat Logs',
    'CPL high energy ultra dry heat log blocks (pack of 8) for open fires, chimineas and multi-fuel stoves.',
    3.85,
    40,
    5.0,
    15,
    '/fuel-heat-log-blocks-8.png',
    false,
    false,
    '{"fuel_type": "Heat Log Blocks", "quantity": "Pack of 8", "is_active": true, "usage_type": "DOMESTIC"}'::jsonb,
    now(),
    now()
  ),
  (
    'Lumpwood Charcoal - 4kg',
    'lumpwood-charcoal-4kg',
    'Homefire',
    'coal-fuels',
    'Charcoal',
    'Homefire 100% natural lumpwood charcoal (4kg) – fast lighting, high heat for authentic barbecue flavor.',
    5.60,
    50,
    5.0,
    22,
    '/fuel-lumpwood-charcoal-4kg.png',
    true,
    false,
    '{"fuel_type": "Lumpwood Charcoal", "weight": "4kg", "is_active": true, "usage_type": "DOMESTIC"}'::jsonb,
    now(),
    now()
  ),
  (
    'Small Instant Barbecue',
    'small-instant-barbecue',
    'Kingfisher',
    'coal-fuels',
    'Barbecue',
    'Kingfisher instant disposable barbecue – all in one pack, easy to light, ready in 20 minutes, burns for up to 1.5 hours.',
    3.00,
    40,
    5.0,
    11,
    '/fuel-small-instant-bbq.png',
    false,
    false,
    '{"fuel_type": "Disposable BBQ", "is_active": true, "usage_type": "DOMESTIC"}'::jsonb,
    now(),
    now()
  ),
  (
    'Large Party Barbecue',
    'large-party-barbecue',
    'Big K',
    'coal-fuels',
    'Barbecue',
    'Big K party size disposable instant BBQ – extra-large cooking surface for family gatherings and outdoor parties.',
    7.15,
    35,
    5.0,
    14,
    '/fuel-large-party-bbq.png',
    true,
    false,
    '{"fuel_type": "Party Disposable BBQ", "is_active": true, "usage_type": "DOMESTIC"}'::jsonb,
    now(),
    now()
  ),
  (
    'BBQ Lighter Fluid 1L',
    'bbq-lighter-fluid-1l',
    'Big K',
    'coal-fuels',
    'Firelighters',
    'Big K premium barbecue lighting fluid (1 Litre bottle) with safety cap for charcoal barbecues.',
    4.00,
    60,
    5.0,
    18,
    '/fuel-bbq-lighter-fluid-1l.png',
    false,
    false,
    '{"fuel_type": "Lighter Fluid", "volume": "1L", "is_active": true, "usage_type": "DOMESTIC"}'::jsonb,
    now(),
    now()
  )
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  category_slug = EXCLUDED.category_slug,
  subcategory = EXCLUDED.subcategory,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  stock = EXCLUDED.stock,
  image_url = EXCLUDED.image_url,
  specs = EXCLUDED.specs,
  updated_at = now();
