-- Migration 00036: Sync real Propane Gas refill products (6kg, 13kg, 19kg, 47kg)
-- Updates existing propane records with exact names, prices, images, and cylinder exchange metadata

INSERT INTO public.products (
  id,
  name,
  slug,
  brand,
  category_id,
  category_slug,
  subcategory,
  description,
  price,
  stock,
  rating,
  reviews_count,
  image_url,
  is_featured,
  is_offer,
  specs,
  created_at,
  updated_at
) VALUES
  (
    '04e2ef7d-203c-45f5-8183-97958debae88',
    'Calor Gas Propane - 6kg Refill',
    'calor-gas-propane-6kg-refill',
    'Calor',
    'c78e60e3-bf94-4015-b8a6-a9c5a487fcf7',
    'gas',
    'Propane Cylinders',
    '6kg Propane gas cylinder refill with standard POL screw connection for caravans, campervans and outdoor catering. Requires an empty cylinder exchange on delivery.',
    32.90,
    25,
    5.0,
    16,
    '/calor-propane-6kg.png',
    true,
    false,
    '{"gas_type": "Propane", "is_active": true, "is_refill": true, "usage_type": "DOMESTIC", "product_mode": "Refill / Cylinder Exchange", "refill_price": 32.90, "cylinder_size": "6kg", "deposit_price": 34.99, "empty_cylinder_required": true}'::jsonb,
    now(),
    now()
  ),
  (
    'ca5ba722-845b-4efe-8db5-ae8a6a2522ef',
    'Calor Gas Propane - 13kg Refill',
    'calor-gas-propane-13kg-refill',
    'Calor',
    'c78e60e3-bf94-4015-b8a6-a9c5a487fcf7',
    'gas',
    'Propane Cylinders',
    '13kg Propane gas cylinder refill with standard POL screw connection for whole-home heating, cooking and light commercial use. Requires an empty cylinder exchange on delivery.',
    50.00,
    30,
    5.0,
    24,
    '/calor-propane-13kg.png',
    true,
    false,
    '{"gas_type": "Propane", "is_active": true, "is_refill": true, "usage_type": "DOMESTIC", "product_mode": "Refill / Cylinder Exchange", "refill_price": 50.00, "cylinder_size": "13kg", "deposit_price": 39.99, "empty_cylinder_required": true}'::jsonb,
    now(),
    now()
  ),
  (
    'b09f7d15-90be-42ac-b1f9-0fce9162a3ce',
    'Calor Gas Propane - 19kg Refill',
    'calor-gas-propane-19kg-refill',
    'Calor',
    'c78e60e3-bf94-4015-b8a6-a9c5a487fcf7',
    'gas',
    'Propane Cylinders',
    '19kg Propane gas cylinder refill with standard POL screw connection for commercial kitchens, catering trailers and space heaters. Requires an empty cylinder exchange on delivery.',
    62.00,
    20,
    5.0,
    12,
    '/calor-propane-19kg.png',
    true,
    false,
    '{"gas_type": "Propane", "is_active": true, "is_refill": true, "usage_type": "COMMERCIAL", "product_mode": "Refill / Cylinder Exchange", "refill_price": 62.00, "cylinder_size": "19kg", "deposit_price": 49.99, "empty_cylinder_required": true}'::jsonb,
    now(),
    now()
  ),
  (
    'a726b178-9281-4441-bd96-ea2f01f0496f',
    'Calor Gas Propane - 47kg Refill',
    'calor-gas-propane-47kg-refill',
    'Calor',
    'c78e60e3-bf94-4015-b8a6-a9c5a487fcf7',
    'gas',
    'Propane Cylinders',
    '47kg Propane gas cylinder refill with standard POL screw connection for central heating packs, drying kilns and large commercial installations. Requires an empty cylinder exchange on delivery.',
    113.50,
    15,
    5.0,
    20,
    '/calor-propane-47kg.png',
    true,
    false,
    '{"gas_type": "Propane", "is_active": true, "is_refill": true, "usage_type": "COMMERCIAL", "product_mode": "Refill / Cylinder Exchange", "refill_price": 113.50, "cylinder_size": "47kg", "deposit_price": 69.99, "empty_cylinder_required": true}'::jsonb,
    now(),
    now()
  )
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  slug = EXCLUDED.slug,
  brand = EXCLUDED.brand,
  category_id = EXCLUDED.category_id,
  category_slug = EXCLUDED.category_slug,
  subcategory = EXCLUDED.subcategory,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  specs = EXCLUDED.specs,
  updated_at = now();
