-- Migration 00044: Gas Appliances Mobile Heaters Setup
-- Inserts/updates the 7 Mobile Heaters products in public.products

INSERT INTO public.products (
  name,
  slug,
  brand,
  category_slug,
  subcategory,
  description,
  price,
  stock,
  rating,
  reviews_count,
  image_url,
  is_featured,
  is_offer,
  specs,
  created_at,
  updated_at
) VALUES
  (
    'Lifestyle Catalytic',
    'lifestyle-catalytic',
    'Lifestyle',
    'gas-appliances',
    'Mobile Heaters',
    'Lifestyle Catalytic gas cabinet heater – premium European made catalytic flueless heater with clean, even radiant heat output and safety oxygen depletion sensor.',
    142.95,
    15,
    5.0,
    19,
    '/heater-lifestyle-catalytic.png',
    false,
    false,
    '{"type": "Catalytic Gas Heater", "origin": "Made in EU", "brand": "Lifestyle"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    'Lifestyle Mini Black',
    'lifestyle-mini-black',
    'Lifestyle',
    'gas-appliances',
    'Mobile Heaters',
    'Lifestyle Mini Black portable radiant gas heater – compact indoor cabinet heater designed for small spaces with 3 heat settings and castor wheels.',
    99.95,
    20,
    5.0,
    24,
    '/heater-lifestyle-mini-black.png',
    false,
    false,
    '{"type": "Radiant Cabinet Heater", "color": "Black", "brand": "Lifestyle"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    'Lifestyle Mini Red',
    'lifestyle-mini-red',
    'Lifestyle',
    'gas-appliances',
    'Mobile Heaters',
    'Lifestyle Mini Red portable radiant gas heater – stylish red gloss finish compact gas heater with electronic ignition and integrated safety cut-off.',
    99.95,
    18,
    5.0,
    16,
    '/heater-lifestyle-mini-red.png',
    false,
    false,
    '{"type": "Radiant Cabinet Heater", "color": "Red Gloss", "brand": "Lifestyle"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    'Manhatten Living Flame',
    'manhatten-living-flame',
    'Lifestyle',
    'gas-appliances',
    'Mobile Heaters',
    'Manhatten Living Flame gas heater – contemporary stove design featuring real living flame effect and chrome trim. No chimney or flue required.',
    269.99,
    10,
    5.0,
    32,
    '/heater-manhatten-living-flame.png',
    false,
    false,
    '{"type": "Living Flame Gas Heater", "effect": "Real Flame Effect", "brand": "Lifestyle"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    'Phoenix Cabinet Heater',
    'phoenix-cabinet-heater',
    'Phoenix',
    'gas-appliances',
    'Mobile Heaters',
    'Phoenix Cabinet Heater – robust and efficient mobile gas heater with high-grade infrared ceramic plaques, easy-glide castors, and hose & regulator included.',
    99.99,
    25,
    5.0,
    21,
    '/heater-phoenix-cabinet.png',
    false,
    false,
    '{"type": "Infrared Cabinet Heater", "power": "4.2kW", "brand": "Phoenix"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    'Provence Flame Effect Heater',
    'provence-flame-effect-heater',
    'Universal Innovations',
    'gas-appliances',
    'Mobile Heaters',
    'Provence Flame Effect portable gas heater – rustic traditional cast-iron style heater with authentic dancing gas flames and double safety devices.',
    340.00,
    8,
    5.0,
    29,
    '/heater-provence-flame-effect.png',
    false,
    false,
    '{"type": "Cast Iron Style Heater", "effect": "Real Flame Effect", "brand": "Universal Innovations"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    'Superheat Model H46',
    'superheat-model-h46',
    'Superheat',
    'gas-appliances',
    'Mobile Heaters',
    'Superheat Model H46 portable infrared gas heater – 4.2kW triple plaque cabinet heater providing fast and reliable warmth for home, workshop or office.',
    129.95,
    15,
    5.0,
    14,
    '/heater-superheat-model-h46.png',
    false,
    false,
    '{"type": "Infrared Gas Heater", "model": "H46", "power": "4.2kW", "brand": "Superheat"}'::jsonb,
    NOW(),
    NOW()
  )
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  category_slug = EXCLUDED.category_slug,
  subcategory = EXCLUDED.subcategory,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  stock = EXCLUDED.stock,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  image_url = EXCLUDED.image_url,
  is_featured = EXCLUDED.is_featured,
  is_offer = EXCLUDED.is_offer,
  specs = EXCLUDED.specs,
  updated_at = NOW();
