-- Migration 00043: Gas Appliances Barbecues Setup
-- Updates the "Gas Appliances" category subcategories (Barbecues, Mobile Heaters, Patio Heaters, Camping)
-- and inserts/updates the 13 real Barbecues products in public.products

-- 1. Insert / Update Gas Appliances category
INSERT INTO public.categories (
  name,
  slug,
  icon,
  description,
  subcategories,
  display_order,
  is_active
) VALUES (
  'Gas Appliances',
  'gas-appliances',
  'CookingPot',
  'Gas appliances for all your heating, barbecue and camping needs.',
  ARRAY[
    'Barbecues',
    'Mobile Heaters',
    'Patio Heaters',
    'Camping'
  ],
  7,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  icon = EXCLUDED.icon,
  description = EXCLUDED.description,
  subcategories = EXCLUDED.subcategories,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active;

-- 2. Insert or update the 13 Barbecue products
INSERT INTO public.products (
  name,
  slug,
  brand,
  category_slug,
  subcategory,
  description,
  price,
  stock,
  rating,
  reviews_count,
  image_url,
  is_featured,
  is_offer,
  specs,
  created_at,
  updated_at
) VALUES
  (
    'Oil Drum Charcoal BBQ',
    'oil-drum-charcoal-bbq',
    'Char-Broil',
    'gas-appliances',
    'Barbecues',
    'Oil Drum Charcoal BBQ – heavy-duty classic charcoal barrel barbecue with warming rack, side handles, and wheeled mobility.',
    72.00,
    20,
    5.0,
    14,
    '/bbq-oil-drum-charcoal.png',
    false,
    false,
    '{"type": "Charcoal Barbecue", "fuel": "Charcoal", "brand": "Char-Broil"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    'Outdoor BBQ Fire Pit Heater',
    'outdoor-bbq-fire-pit-heater',
    'Char-Broil',
    'gas-appliances',
    'Barbecues',
    'Outdoor BBQ Fire Pit Heater – dual-purpose garden fire pit with stainless steel outer ring, safety spark mesh guard, and barbecue cooking grate.',
    69.65,
    25,
    5.0,
    19,
    '/bbq-outdoor-fire-pit-heater.png',
    false,
    false,
    '{"type": "Fire Pit & BBQ", "fuel": "Wood / Charcoal", "brand": "Char-Broil"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    'Performance Pro S 3',
    'performance-pro-s-3',
    'Char-Broil',
    'gas-appliances',
    'Barbecues',
    'Char-Broil Performance Pro S 3 – 3-burner TRU-Infrared gas barbecue with stainless steel hood, side burner, and cast iron grates.',
    0.00,
    10,
    5.0,
    26,
    '/bbq-performance-pro-s-3.png',
    false,
    false,
    '{"burners": 3, "technology": "TRU-Infrared", "call_for_price": true, "brand": "Char-Broil"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    'Professional Core B 3',
    'professional-core-b-3',
    'Char-Broil',
    'gas-appliances',
    'Barbecues',
    'Char-Broil Professional Core B 3 – premium 3-burner black finish gas barbecue with TRU-Infrared cooking system and electronic SureFire ignition.',
    0.00,
    10,
    5.0,
    22,
    '/bbq-professional-core-b-3.png',
    false,
    false,
    '{"burners": 3, "finish": "Black Core", "technology": "TRU-Infrared", "call_for_price": true, "brand": "Char-Broil"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    'Professional Core B 4',
    'professional-core-b-4',
    'Char-Broil',
    'gas-appliances',
    'Barbecues',
    'Char-Broil Professional Core B 4 – extra-large 4-burner gas barbecue with side burner, cast iron grates, and high-heat sear burner.',
    0.00,
    8,
    5.0,
    18,
    '/bbq-professional-core-b-4.png',
    false,
    false,
    '{"burners": 4, "finish": "Black Core", "technology": "TRU-Infrared", "call_for_price": true, "brand": "Char-Broil"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    'Professional Pro S 2',
    'professional-pro-s-2',
    'Char-Broil',
    'gas-appliances',
    'Barbecues',
    'Char-Broil Professional Pro S 2 – compact 2-burner stainless steel barbecue featuring patented TRU-Infrared cooking system for 50% juicier food.',
    459.00,
    15,
    5.0,
    31,
    '/bbq-professional-pro-s-2.png',
    false,
    false,
    '{"burners": 2, "finish": "Stainless Steel", "technology": "TRU-Infrared", "brand": "Char-Broil"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    'Professional Pro S 3',
    'professional-pro-s-3',
    'Char-Broil',
    'gas-appliances',
    'Barbecues',
    'Char-Broil Professional Pro S 3 – 3-burner stainless steel gas barbecue with high-power sear burner, LED illuminated control knobs, and TRU-Infrared technology.',
    665.00,
    12,
    5.0,
    45,
    '/bbq-professional-pro-s-3.png',
    false,
    false,
    '{"burners": 3, "finish": "Stainless Steel", "technology": "TRU-Infrared", "brand": "Char-Broil"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    'Smart-E',
    'smart-e',
    'Char-Broil',
    'gas-appliances',
    'Barbecues',
    'Char-Broil SMART-E – 100% electric barbecue delivering true grill performance without gas or charcoal. SMART PRECISION temperature control from 90°C to 370°C.',
    599.00,
    15,
    5.0,
    28,
    '/bbq-smart-e.png',
    false,
    false,
    '{"type": "Electric Grill", "technology": "SMART-E Precision", "power": "2400W", "brand": "Char-Broil"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    'Smoker BBQ',
    'smoker-bbq',
    'Char-Broil',
    'gas-appliances',
    'Barbecues',
    'Smoker BBQ – premium offset smoker and charcoal barbecue with front access door, chimney damper, and spacious lower storage shelf.',
    149.00,
    20,
    5.0,
    17,
    '/bbq-smoker.png',
    false,
    false,
    '{"type": "Smoker & Charcoal", "brand": "Char-Broil"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    'Ultimate 3200',
    'ultimate-3200',
    'Char-Broil',
    'gas-appliances',
    'Barbecues',
    'Char-Broil Ultimate 3200 – premium 3-burner outdoor kitchen barbecue island crafted from marine-grade 304 stainless steel with granite-look countertop.',
    1300.00,
    6,
    5.0,
    15,
    '/bbq-ultimate-3200.png',
    false,
    false,
    '{"type": "Outdoor Kitchen BBQ", "material": "304 Stainless Steel", "brand": "Char-Broil"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    'Ultimate BBQ Package',
    'ultimate-bbq-package',
    'Char-Broil',
    'gas-appliances',
    'Barbecues',
    'Char-Broil Ultimate BBQ Package – complete L-shaped luxury modular outdoor kitchen including Ultimate 3200 Grill, Entertainment Sink Module, and Corner Unit.',
    3100.00,
    4,
    5.0,
    9,
    '/bbq-ultimate-package.png',
    false,
    false,
    '{"type": "Complete Modular Kitchen", "material": "304 Stainless Steel", "brand": "Char-Broil"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    'Ultimate Corner Module',
    'ultimate-corner-module',
    'Char-Broil',
    'gas-appliances',
    'Barbecues',
    'Char-Broil Ultimate Corner Module – 90-degree connecting corner unit with granite worktop and double-door storage cabinet for custom outdoor kitchen layouts.',
    565.00,
    10,
    5.0,
    11,
    '/bbq-ultimate-corner-module.png',
    false,
    false,
    '{"type": "Modular Corner Unit", "brand": "Char-Broil"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    'Ultimate Entertainment',
    'ultimate-entertainment',
    'Char-Broil',
    'gas-appliances',
    'Barbecues',
    'Char-Broil Ultimate Entertainment Module – outdoor kitchen preparation station featuring running-water sink faucet, integrated ice bucket / cooler, and storage drawers.',
    1300.00,
    8,
    5.0,
    16,
    '/bbq-ultimate-entertainment.png',
    false,
    false,
    '{"type": "Entertainment & Sink Module", "material": "304 Stainless Steel", "brand": "Char-Broil"}'::jsonb,
    NOW(),
    NOW()
  )
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  category_slug = EXCLUDED.category_slug,
  subcategory = EXCLUDED.subcategory,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  stock = EXCLUDED.stock,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  image_url = EXCLUDED.image_url,
  is_featured = EXCLUDED.is_featured,
  is_offer = EXCLUDED.is_offer,
  specs = EXCLUDED.specs,
  updated_at = NOW();
