-- Migration 00046: Gas Appliances Camping Setup
-- Inserts/updates the 8 Camping products in public.products

INSERT INTO public.products (
  name,
  slug,
  brand,
  category_slug,
  subcategory,
  description,
  price,
  stock,
  rating,
  reviews_count,
  image_url,
  is_featured,
  is_offer,
  specs,
  created_at,
  updated_at
) VALUES
  (
    'Camping 206L',
    'camping-206l',
    'Campingaz',
    'gas-appliances',
    'Camping',
    'Campingaz Camping 206L – high-power 80W portable camping gas lantern with globe protection guard and integrated carry handle.',
    12.00,
    20,
    5.0,
    14,
    '/camping-206l.png',
    false,
    false,
    '{"type": "Camping Gas Lantern", "power": "80W", "brand": "Campingaz"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    'Camping 206S',
    'camping-206s',
    'Campingaz',
    'gas-appliances',
    'Camping',
    'Campingaz Camping 206S – compact 1250W single burner portable camping stove with wide pan supports and stable cartridge base.',
    10.00,
    25,
    5.0,
    18,
    '/camping-206s.png',
    false,
    false,
    '{"type": "Single Burner Camping Stove", "power": "1250W", "brand": "Campingaz"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    'Camp Bistro 3 Camping Gas Stove',
    'camp-bistro-3-camping-gas-stove',
    'Campingaz',
    'gas-appliances',
    'Camping',
    'Campingaz Camp Bistro 3 Camping Gas Stove – classic tabletop portable gas cooker with automatic piezo ignition and durable carry case included.',
    20.50,
    30,
    5.0,
    26,
    '/camping-camp-bistro-3.png',
    false,
    false,
    '{"type": "Tabletop Gas Stove", "brand": "Campingaz", "ignition": "Piezo"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    'Instaflam Stove',
    'instaflam-stove',
    'Instaflam',
    'gas-appliances',
    'Camping',
    'Instaflam Stove – ultra-compact lightweight backpacking gas stove with fold-out pan supports and fine flame control knob.',
    3.50,
    40,
    5.0,
    12,
    '/camping-instaflam-stove.png',
    false,
    false,
    '{"type": "Portable Camping Stove", "brand": "Instaflam"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    'Camping Chef CV Gas Stove',
    'camping-chef-cv-gas-stove',
    'Campingaz',
    'gas-appliances',
    'Camping',
    'Campingaz Camping Chef CV Gas Stove – double burner camping stove with downward grill for toasting, briefcase lid closure, and CV cartridge compatibility.',
    44.95,
    15,
    5.0,
    22,
    '/camping-chef-cv.png',
    false,
    false,
    '{"type": "Double Burner & Grill", "power": "4900W", "brand": "Campingaz"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    'Bleuet CV270L',
    'bleuet-cv270l',
    'Campingaz',
    'gas-appliances',
    'Camping',
    'Campingaz Bleuet CV270L – reliable outdoor gas lantern with frosted globe for soft diffused campsite illumination, using Easy Clic Plus connection.',
    10.00,
    18,
    5.0,
    11,
    '/camping-bleuet-cv270l.png',
    false,
    false,
    '{"type": "Camping Gas Lantern", "brand": "Campingaz"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    'Bleuet CV270S',
    'bleuet-cv270s',
    'Campingaz',
    'gas-appliances',
    'Camping',
    'Campingaz Bleuet CV270S – 1200W pocket-sized camping gas burner with Easy Clic cartridge connection and rugged serrated pan support arms.',
    7.00,
    22,
    5.0,
    19,
    '/camping-bleuet-cv270s.png',
    false,
    false,
    '{"type": "Single Burner Camping Stove", "power": "1200W", "brand": "Campingaz"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    'Compact Double Burner Stove',
    'compact-double-burner-stove',
    'SunnGas',
    'gas-appliances',
    'Camping',
    'SunnGas Compact Double Burner Stove – heavy-duty enameled dual-burner family camping stove with individual burner control and chrome wire cooking grid.',
    20.00,
    16,
    5.0,
    17,
    '/camping-compact-double-burner.png',
    false,
    false,
    '{"type": "Dual Burner Camping Stove", "brand": "SunnGas"}'::jsonb,
    NOW(),
    NOW()
  )
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  category_slug = EXCLUDED.category_slug,
  subcategory = EXCLUDED.subcategory,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  stock = EXCLUDED.stock,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  image_url = EXCLUDED.image_url,
  is_featured = EXCLUDED.is_featured,
  is_offer = EXCLUDED.is_offer,
  specs = EXCLUDED.specs,
  updated_at = NOW();
