-- Migration 00047: Garden Category Setup
-- Inserts/updates the 4 Garden products in public.products

INSERT INTO public.products (
  name,
  slug,
  brand,
  category_slug,
  subcategory,
  description,
  price,
  stock,
  rating,
  reviews_count,
  image_url,
  is_featured,
  is_offer,
  specs,
  created_at,
  updated_at
) VALUES
  (
    'SylvaGrow® Multi-Purpose Compost 15L',
    'sylvagrow-multi-purpose-compost-15l',
    'Melcourt',
    'garden',
    'Compost',
    'Melcourt SylvaGrow® Multi-Purpose Compost (15L) – 100% peat-free professional quality compost ideal for potting, containers, hanging baskets, and garden planting.',
    2.50,
    50,
    5.0,
    22,
    '/garden-sylvagrow-15l.png',
    false,
    false,
    '{"brand": "Melcourt", "volume": "15L", "type": "Multi-Purpose Peat-Free Compost", "endorsed_by": "RHS"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    'SylvaGrow® Multi-Purpose Compost 40L',
    'sylvagrow-multi-purpose-compost-40l',
    'Melcourt',
    'garden',
    'Compost',
    'Melcourt SylvaGrow® Multi-Purpose Compost (40L) – premium 100% peat-free growing medium endorsed by the RHS for seed sowing, pricking out, potting, and bed planting.',
    6.50,
    60,
    5.0,
    38,
    '/garden-sylvagrow-40l.png',
    false,
    false,
    '{"brand": "Melcourt", "volume": "40L", "type": "Multi-Purpose Peat-Free Compost", "endorsed_by": "RHS"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    'SylvaGrow Organic Planter',
    'sylvagrow-organic-planter',
    'Melcourt',
    'garden',
    'Planters',
    'Melcourt SylvaGrow® Organic Planter – 100% peat-free deep grow bag planter enriched with balanced organic nutrients, ideal for tomatoes, peppers, cucumbers, and salad crops.',
    5.25,
    35,
    5.0,
    19,
    '/garden-sylvagrow-planter.png',
    false,
    false,
    '{"brand": "Melcourt", "type": "Organic Peat-Free Planter Grow Bag", "endorsed_by": "RHS"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    'Melcourt Decorative Bark Large Nuggets Mulch 60L',
    'melcourt-decorative-bark-large-nuggets-mulch-60l',
    'Melcourt',
    'garden',
    'Bark & Mulch',
    'Melcourt Decorative Bark Large Nuggets Mulch (60L) – long-lasting British chunky pine bark mulch for decorative borders, moisture retention, weed suppression, and garden landscape paths.',
    10.30,
    45,
    5.0,
    27,
    '/garden-melcourt-bark-60l.png',
    false,
    false,
    '{"brand": "Melcourt", "volume": "60L", "type": "Decorative Chunky Bark Nuggets", "endorsed_by": "RHS"}'::jsonb,
    NOW(),
    NOW()
  )
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  category_slug = EXCLUDED.category_slug,
  subcategory = EXCLUDED.subcategory,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  stock = EXCLUDED.stock,
  image_url = EXCLUDED.image_url,
  specs = EXCLUDED.specs,
  updated_at = NOW();
