-- Migration 00045: Gas Appliances Patio Heaters Setup
-- Inserts/updates the 6 Patio Heaters products in public.products

INSERT INTO public.products (
  name,
  slug,
  brand,
  category_slug,
  subcategory,
  description,
  price,
  stock,
  rating,
  reviews_count,
  image_url,
  is_featured,
  is_offer,
  specs,
  created_at,
  updated_at
) VALUES
  (
    '13kW Heat Focus Patio Heater Charcoal',
    '13kw-heat-focus-patio-heater-charcoal',
    'Lifestyle',
    'gas-appliances',
    'Patio Heaters',
    '13kW Heat Focus Patio Heater Charcoal – high-performance outdoor gas patio heater with revolutionary heat focus directional reflector for optimal heating efficiency.',
    199.99,
    15,
    5.0,
    18,
    '/patio-heater-13kw-charcoal.png',
    false,
    false,
    '{"type": "Gas Patio Heater", "output": "13kW", "finish": "Charcoal", "features": "Heat Focus Reflector"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    '15kW Heat Focus Patio Heater White',
    '15kw-heat-focus-patio-heater-white',
    'Lifestyle',
    'gas-appliances',
    'Patio Heaters',
    '15kW Heat Focus Patio Heater White – premium commercial-grade outdoor gas heater with adjustable heat reflector, sleek white gloss body, and anti-tilt safety shut-off.',
    319.99,
    10,
    5.0,
    22,
    '/patio-heater-15kw-white.png',
    false,
    false,
    '{"type": "Gas Patio Heater", "output": "15kW", "finish": "White", "features": "Heat Focus Reflector"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    'Free Standing Patio Heater',
    'free-standing-patio-heater',
    'Kingfisher',
    'gas-appliances',
    'Patio Heaters',
    'Free Standing Patio Heater – versatile infrared quartz electric garden heater with 3 heat settings, adjustable pole height, and heavy stable base.',
    60.95,
    20,
    5.0,
    15,
    '/patio-heater-free-standing.png',
    false,
    false,
    '{"type": "Electric Free Standing Heater", "brand": "Kingfisher", "features": "Adjustable Height"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    'Outdoor BBQ Fire Pit Heater',
    'outdoor-bbq-fire-pit-heater',
    'Char-Broil',
    'gas-appliances',
    'Patio Heaters',
    'Outdoor BBQ Fire Pit Heater – dual-purpose circular garden fire pit and barbecue with spark mesh guard, chrome cooking grill, and heat-resistant finish.',
    69.65,
    25,
    5.0,
    27,
    '/patio-heater-outdoor-fire-pit.png',
    false,
    false,
    '{"type": "Fire Pit & BBQ", "fuel": "Wood / Charcoal", "features": "Spark Guard & Grate"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    'Outdoor Gas Patio Heater',
    'outdoor-gas-patio-heater',
    'Lifestyle',
    'gas-appliances',
    'Patio Heaters',
    'Outdoor Gas Patio Heater – classic tall outdoor mushroom heater with powder-coated green finish, integrated cylinder enclosure, and electronic ignition.',
    162.00,
    12,
    5.0,
    19,
    '/patio-heater-outdoor-gas-tall.png',
    false,
    false,
    '{"type": "Tall Gas Patio Heater", "finish": "Green", "features": "Cylinder Housing & Wheeled"}'::jsonb,
    NOW(),
    NOW()
  ),
  (
    'Outdoor Table Top Patio Heater',
    'outdoor-table-top-patio-heater',
    'Lifestyle',
    'gas-appliances',
    'Patio Heaters',
    'Outdoor Table Top Patio Heater – compact garden dining table heater with stainless steel burner, safety guard, and anti-tilt mechanism.',
    74.00,
    16,
    5.0,
    14,
    '/patio-heater-table-top.png',
    false,
    false,
    '{"type": "Table Top Gas Patio Heater", "finish": "Green", "features": "Compact Tabletop Design"}'::jsonb,
    NOW(),
    NOW()
  )
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  category_slug = EXCLUDED.category_slug,
  subcategory = EXCLUDED.subcategory,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  stock = EXCLUDED.stock,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  image_url = EXCLUDED.image_url,
  is_featured = EXCLUDED.is_featured,
  is_offer = EXCLUDED.is_offer,
  specs = EXCLUDED.specs,
  updated_at = NOW();
